### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by davewongillies** [fgtdev/fortios-sdk-go#1]
Over in terraform-provider-fortios in the [`go.mod`](https://github.com/terraform-providers/terraform-provider-fortios/blob/master/go.mod#L15) you've got this line:

```
	github.com/fgtdev/fortios-sdk-go v1.0.0
```

When I run a `go mod vendor` in terraform-provider-fortios, it pulls in v1.0.0 of this repo, which means I lose the changes to https://github.com/terraform-providers/terraform-provider-fortios/blob/master/vendor/github.com/fgtdev/fortios-sdk-go/sdkcore/forticlient.go (which you seem to have done in the `vendor` directory of that repo), and them I'm not able to compile it.

Can you please tag a new release, then update `go.mod` in terraform-provider-fortios.

Thanks!

**Comment by frankshen01** [comment]
Hi, @davewongillies, thank you for your contribution.  Sorry for taking so long to get back to this. Tag v1.0.1 has been added and updated to the new version. The go.mod at  https://github.com/terraform-providers/terraform-provider-fortios is updated too,  `github.com/fgtdev/fortios-sdk-go v1.0.1` .
